# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ytdlp.v1 import reserse_executor_pb2 as ytdlp_dot_v1_dot_reserse__executor__pb2


class ReverseExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TaskStream = channel.stream_stream(
                '/ytdlp.v1.ReverseExecutor/TaskStream',
                request_serializer=ytdlp_dot_v1_dot_reserse__executor__pb2.ClientMessage.SerializeToString,
                response_deserializer=ytdlp_dot_v1_dot_reserse__executor__pb2.ServerMessage.FromString,
                _registered_method=True)


class ReverseExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TaskStream(self, request_iterator, context):
        """iPhone initiates a long-lived connection and receives tasks over this stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReverseExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TaskStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TaskStream,
                    request_deserializer=ytdlp_dot_v1_dot_reserse__executor__pb2.ClientMessage.FromString,
                    response_serializer=ytdlp_dot_v1_dot_reserse__executor__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ytdlp.v1.ReverseExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ytdlp.v1.ReverseExecutor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReverseExecutor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TaskStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ytdlp.v1.ReverseExecutor/TaskStream',
            ytdlp_dot_v1_dot_reserse__executor__pb2.ClientMessage.SerializeToString,
            ytdlp_dot_v1_dot_reserse__executor__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
