# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ytdlp.v1 import reverse_executor_pb2 as ytdlp_dot_v1_dot_reverse__executor__pb2


class ReverseExecutorStub(object):
    """ReverseExecutor allows yt-dlp to offload every HTTP request to a remote client
    (e.g. an iOS device). The typical client workflow is:

    1. Open TaskStream() and immediately send a ClientMessage{hello} describing the
    device, user agent, and any preloaded cookies.
    2. Optionally send ClientMessage{task_request} to ask the server to process a
    URL. The server responds with ServerMessage{task_accepted}.
    3. For each ServerMessage{request}, perform the HTTP call locally and return
    the result with ClientMessage{response}. Large bodies may be streamed with
    ClientMessage{chunk}.
    4. When yt-dlp finishes extraction it emits ServerMessage{extract_result}. The
    client can then close the stream or enqueue another TaskRequest.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TaskStream = channel.stream_stream(
                '/ytdlp.v1.ReverseExecutor/TaskStream',
                request_serializer=ytdlp_dot_v1_dot_reverse__executor__pb2.ClientMessage.SerializeToString,
                response_deserializer=ytdlp_dot_v1_dot_reverse__executor__pb2.ServerMessage.FromString,
                _registered_method=True)


class ReverseExecutorServicer(object):
    """ReverseExecutor allows yt-dlp to offload every HTTP request to a remote client
    (e.g. an iOS device). The typical client workflow is:

    1. Open TaskStream() and immediately send a ClientMessage{hello} describing the
    device, user agent, and any preloaded cookies.
    2. Optionally send ClientMessage{task_request} to ask the server to process a
    URL. The server responds with ServerMessage{task_accepted}.
    3. For each ServerMessage{request}, perform the HTTP call locally and return
    the result with ClientMessage{response}. Large bodies may be streamed with
    ClientMessage{chunk}.
    4. When yt-dlp finishes extraction it emits ServerMessage{extract_result}. The
    client can then close the stream or enqueue another TaskRequest.
    """

    def TaskStream(self, request_iterator, context):
        """Client maintains a long-lived bidirectional stream and handles tasks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReverseExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TaskStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TaskStream,
                    request_deserializer=ytdlp_dot_v1_dot_reverse__executor__pb2.ClientMessage.FromString,
                    response_serializer=ytdlp_dot_v1_dot_reverse__executor__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ytdlp.v1.ReverseExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ytdlp.v1.ReverseExecutor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReverseExecutor(object):
    """ReverseExecutor allows yt-dlp to offload every HTTP request to a remote client
    (e.g. an iOS device). The typical client workflow is:

    1. Open TaskStream() and immediately send a ClientMessage{hello} describing the
    device, user agent, and any preloaded cookies.
    2. Optionally send ClientMessage{task_request} to ask the server to process a
    URL. The server responds with ServerMessage{task_accepted}.
    3. For each ServerMessage{request}, perform the HTTP call locally and return
    the result with ClientMessage{response}. Large bodies may be streamed with
    ClientMessage{chunk}.
    4. When yt-dlp finishes extraction it emits ServerMessage{extract_result}. The
    client can then close the stream or enqueue another TaskRequest.
    """

    @staticmethod
    def TaskStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ytdlp.v1.ReverseExecutor/TaskStream',
            ytdlp_dot_v1_dot_reverse__executor__pb2.ClientMessage.SerializeToString,
            ytdlp_dot_v1_dot_reverse__executor__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
